nervosnetwork/ckb-sdk-rust

examples/transfer_from_omnilock_multisig.rs, src/unlock/omni_lock.rs, src/unlock/signer.rs
1. Add a example to do omnilock multisig transfer, so the code can be verified in a test chain.
2. When get MultisigConfig from OmniLockConfig, return an Option<&MultisigConfig> so user can decide whether to panic or not.
=> test: Add example to do omnilock multisig transfer.

Cargo.toml, src/traits/default_impls.rs, src/tx_builder/mod.rs, src/tx_builder/omni_lock.rs
Since ckb-indexer's [poll interval is 2.0s](https://github.com/nervosnetwork/ckb-indexer/blob/0a6f6f9ec29256662bdb903740996dedb4cbc329/src/main.rs#L62), so we need increase the retry times.
=> fix: improve DefaultCellCollector sync check

Cargo.toml, src/test_util.rs, src/traits/default_impls.rs, src/traits/dummy_impls.rs, src/traits/mod.rs, src/traits/offchain_impls.rs, src/tx_builder/acp.rs, src/tx_builder/cheque.rs, src/tx_builder/dao.rs, src/tx_builder/mod.rs, src/tx_builder/udt/mod.rs, src/unlock/omni_lock.rs, src/unlock/signer.rs, src/unlock/unlocker.rs
Use use anyhow::Error to replace Box &lt;  dyn std::error::Error &gt;
So in a app can use anyhow! directly.
=> refactor: use anyhow::Error to replace Box<dyn std::error::Error>

examples/transfer_from_omnilock.rs, examples/transfer_from_omnilock_ethereum.rs, src/tests/omni_lock.rs, src/unlock/omni_lock.rs
- Use the blake160 hash instead of public key directly for pubkey_hash omnilock;
- Use the keccak160 hash instead of public key directly for ethereum omnilock;
=> refactor: 💡 use hash instead pubkey directly

CHANGELOG.md, Cargo.toml
- Bump ckb-sdk-rust to version 2.4.0
=> chore: 🤖 Bump to 2.4.0

examples/send_ckb_example.rs, examples/send_ckb_multisig_example.rs, src/tests/transaction/sighash.rs, src/transaction/builder/mod.rs, src/transaction/input/mod.rs, src/transaction/mod.rs
This PR refactors `SimpleTransactionBuilder` to simplify the process of building transactions by introducing the `estimate_tx_size` parameter, which makes building transactions simpler and more flexible. the `SmallChangeAction` struct in the original code is an edge case in real-world scenarios for sdk, and is only used when the user needs to transfer all ckb capacity from one address to another address. putting the processing logic of this edge scenario into `SimpleTransactionBuilder` introduces unnecessary complexity, and if needed, we can introduce another builder to specifically handle this requirement via PR later.
=> chore: refactor SimpleTransactionBuilder

.github/workflows/ci.yaml
This [CI job](https://github.com/nervosnetwork/ckb-sdk-rust/actions/runs/5550747875/jobs/10136171728?pr=80) failed, because CI failed to install `cargo-deny`.
Request for review. @quake
=> Fix CI `security-audit` failed to install `cargo-deny`

src/rpc/ckb.rs
Ref: https://github.com/nervosnetwork/ckb/blob/cff0cabc02b7d841053f818330a5e9d07c863130/rpc/src/module/chain.rs#L1605-L1607
The first argument of `get_fee_rate_statistics` should be `target`, and its return type should be an `Option`
@quake Request for review, and we need to publish a new cargo release.
=> Fix `fn get_fee_rate_statistics` return type

src/rpc/ckb.rs, src/rpc/ckb_light_client.rs, src/traits/light_client_impls.rs
This PR want to close #94 and https://github.com/nervosnetwork/ckb-sdk-rust/issues/97
=> Support more RPC for ckb and ckb-light-client

src/rpc/ckb_indexer.rs, src/tests/ckb_indexer_rpc.rs, src/traits/mod.rs, src/transaction/input/mod.rs
Updates:
- Extended the enumeration values for `Partial` in `SearchMode`
- Extended the `output_data` and `output_data_filter_mode` fields for the `SearchKeyFilter`
BREAKING CHANGE: rename `ScriptSearchMode` -> `SearchMode`
=> [BREAKING CHANGE] Extend Indexer PRC `SearchKey` for CKB 0.114

Cargo.toml, src/rpc/ckb_light_client.rs
Ref: nervosnetwork/ckb-light-client#180
=> feat(rpc): add ckb light client rpc method `estimate_cycles`

src/transaction/builder/sudt.rs
In https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0025-simple-udt/0025-simple-udt.md#sudt-cell
```
data:
amount: uint128
type:
code_hash: simple_udt type script
args: owner lock script hash (...)
lock:
<user_defined>
```
sudt's amount type should be u128. Fix #105
=> sudt's amount type should be `u128`

src/transaction/builder/mod.rs
Please make them to be public, so I don't have to copy them to my repository.
=> chore: change visibility of default change builder to be public

src/transaction/handler/sighash.rs
I'm working on a new type script, which requires its own witness.
But when I build a transaction with `ckb_sdk::XxxUnlocker`, the witness will be overridden.
- When sign transactions, the method to handle witnesses are correct.
https://github.com/nervosnetwork/ckb-sdk-rust/blob/c45c4dc0c92bb1f983e878e3ef1876b861ca7038/src/unlock/signer.rs#L109-L119
- But, when call the following code to prepare for sign transactions:
https://github.com/nervosnetwork/ckb-sdk-rust/blob/c45c4dc0c92bb1f983e878e3ef1876b861ca7038/src/transaction/builder/mod.rs#L182
The original witnesses will be overridden.
I tested this patch with my project, it works!
=> fix: override the original witnesses when sign transactions

src/transaction/builder/mod.rs
> [!NOTE]
> The simpler it is, the easier it is to make mistakes.
I made a mistake in #108. :persevere:
Even `DefaultChangeBuilder` is public, but all its fields are private, users couldn't construct it, outside the `ckb-sdk`.
This time, I tested in my local machine before submit this PR.
=> chore: a construct method for default change builder

Cargo.toml, src/rpc/ckb.rs
Need https://github.com/nervosnetwork/ckb-standalone-debugger/pull/130
=> Bump ckb dependencies to v0.116.1

src/transaction/handler/mod.rs, src/transaction/input/mod.rs
```
loop {
if let Some(lock_script) = self.lock_scripts.last() {
let mut query = CellQueryOptions::new_lock(lock_script.clone());
query.script_search_mode = Some(SearchMode::Exact);
if let Some(type_script) = &self.type_script {
query.secondary_script = Some(type_script.clone());
} else {
query.secondary_script_len_range = Some(ValueRangeOption::new_exact(0));
query.data_len_range = Some(ValueRangeOption::new_exact(0));
};
let (live_cells, _capacity) =
self.cell_collector.collect_live_cells(&query, true)?;
if live_cells.is_empty() {
self.lock_scripts.pop();
} else {
self.buffer_inputs = live_cells
.into_iter()
.rev() // reverse the iter, so that the first cell will be consumed while pop
.map(|live_cell| TransactionInput::new(live_cell, 0))
.collect();
break;
}
}
}
```
When …
=> [BUG Fix] Deadlock issue of InputIterator

Cargo.toml, README.md, src/rpc/ckb.rs, src/traits/default_impls.rs
=> Add `include_tx_pool: Option<bool>` param to `get_live_cell`' RPC

src/transaction/builder/sudt.rs, src/transaction/handler/multisig.rs, src/transaction/handler/sighash.rs, src/transaction/handler/sudt.rs, src/transaction/mod.rs, src/types/network_type.rs
Now the udt-init in fiber are using a branch:
https://github.com/nervosnetwork/fiber/blob/ea415e37a12a9cc3d00494d890248736339c3f49/tests/deploy/udt-init/Cargo.toml#L9
It's better to merge the changes into upstream.
=> Add support for customizing local devnet 

src/tests/mod.rs, src/tx_builder/mod.rs
This issue is found in fiber: https://github.com/nervosnetwork/fiber/issues/252
=> Fix tx_builder capacity overflow issue

Cargo.toml, src/unlock/mod.rs
This PR introduces changes to add a new optional feature `rce`. The changes primarily involve updating `sparse-merkle-tree` dep optional, make ckb-sdk-rust easy to compile on wasm target. (Please note that sparse-merkle-tree has c dep, we may remove it in the future)
=> chore : add rce feature

.github/workflows/ci.yaml, Cargo.toml, deny.toml, src/rpc/mod.rs
This PR want to add `fn new_with_cookie(uri: &str)` for `RpcClient`
Ref: https://docs.rs/reqwest/0.12.23/reqwest/blocking/struct.ClientBuilder.html#method.cookie_store
@quake
=> Add new_with_cookie for RpcClient
