- Cargo.toml
- examples/transfer_from_omnilock.rs
- examples/transfer_from_omnilock_ethereum.rs
- src/tests/omni_lock.rs
- src/traits/default_impls.rs
- src/unlock/omni_lock.rs
- src/unlock/signer.rs
- src/util.rs
- Support omnilock ethereum algorithm;
Check List
Tests
- Integration test
- Example to show how to use it
> feat: Add ethereum algorithm to omnilock.

- src/tests/omni_lock.rs
- src/tx_builder/mod.rs
- src/unlock/omni_lock.rs
- src/unlock/signer.rs
- src/unlock/unlocker.rs
Support simple ownerlock style omnilock.
Check List
Tests
Unit test
> feat: 🎸 Support simple ownerlock omnilock

- src/tests/omni_lock.rs
- src/unlock/mod.rs
- src/unlock/omni_lock.rs
- src/unlock/unlocker.rs
Support OmniLock ACP mode
- Unit test
> feat: OmniLock support ACP mode

- src/tests/omni_lock.rs
- src/tx_builder/mod.rs
- src/unlock/omni_lock.rs
Support OmniLock time lock mode
- Unit test
> feat: 🎸 Support omnilock time lock mode

- src/tests/mod.rs
- src/tests/omni_lock.rs
- src/tests/omni_lock_util.rs
- src/tx_builder/mod.rs
- src/tx_builder/omni_lock.rs
- src/unlock/omni_lock.rs
- src/unlock/rc_data.rs
Support put the Omnilock rc_rule into the input list
- Unit test
> feat: Can unlock when rc_rule in input cell list

- CHANGELOG.md
- Cargo.toml
- src/tx_builder/mod.rs
* Bump up to v2.0
* Update CHANGELOG
> chore: bump up to v2.0

- src/rpc/mod.rs
- src/test_util.rs
- src/traits/default_impls.rs
- src/traits/mod.rs
- src/tx_builder/mod.rs
- src/unlock/omni_lock.rs
- src/unlock/rc_data.rs
- src/unlock/signer.rs
- src/unlock/unlocker.rs
Add tests to ensure the anyhow! macro work for the exception enums .
> test: 💍 add tests to ensure anyhow macro work

- CHANGELOG.md
- Cargo.toml
Bump up to v2.1
Update CHANGELOG
> chore: 🤖 bump up to v2.1

- CHANGELOG.md
- Cargo.toml
- examples/transfer_from_multisig.rs
- examples/transfer_from_omnilock.rs
- examples/transfer_from_omnilock_ethereum.rs
- examples/transfer_from_omnilock_multisig.rs
- examples/transfer_from_sighash.rs
- src/rpc/ckb_indexer.rs
- src/traits/default_impls.rs
- src/unlock/rc_data.rs
* `DefaultCellCollector::new` API changed
* remove `IndexerRpcClient::get_indexer_info` rpc method
* rename `IndexerRpcClient::get_tip` to `IndexerRpcClient::get_indexer_tip`
* bump up to `v2.2.0`
> feat: use ckb-indexer from ckb rpc

- CHANGELOG.md
- Cargo.toml
- src/rpc/ckb.rs
- src/tests/mod.rs
- src/traits/default_impls.rs
- src/util.rs
> chore: update ckb to v0.105.1

- examples/chain_transfer_sighash.rs
- src/test_util.rs
- src/traits/default_impls.rs
- src/traits/dummy_impls.rs
- src/traits/light_client_impls.rs
- src/traits/mod.rs
- src/traits/offchain_impls.rs
Support use new transaction outputs as inputs of new transaction, even if the new outputs not on chain yet.
> feat: 🎸 Support offchain transaction build

- CHANGELOG.md
- Cargo.toml
- src/rpc/ckb.rs
- src/rpc/mod.rs
- src/tests/ckb_rpc.rs
- src/tests/mod.rs
- Add with_cycles parameter for RPC get_block/get_block_by_number
- Manually tested with ckb-cli project. https://github.com/nervosnetwork/ckb-cli/pull/533
> feat: 🎸 enable with_cycles for get_block/get_block_by_number and packed rpcs

- CHANGELOG.md
- src/rpc/ckb.rs
- src/rpc/ckb_indexer.rs
- src/tests/ckb_indexer_rpc.rs
- src/tests/mod.rs
- src/traits/mod.rs
- support ckb indexer exact search mode
> feat: 🎸 support ckb indexer exact search mode

- src/rpc/ckb.rs
- src/tests/ckb_rpc.rs
Add rpc function get_transaction_and_witness_proof and verify_transaction_and_witness_proof
> feat: 🎸 Add 2 RPC functions

- examples/send_ckb_multisig_example.rs
- src/transaction/handler/mod.rs
- src/transaction/handler/multisig.rs
- src/transaction/mod.rs
- src/transaction/signer/mod.rs
- src/transaction/signer/multisig.rs
- src/unlock/signer.rs
This add simple multisig transaction to exist simple transaction builder framework
> simple multisig transaction builder

- examples/deploy_script_with_type_id.rs
- examples/send_ckb_example.rs
- examples/send_ckb_multisig_example.rs
- src/tests/transaction/mod.rs
- src/tests/transaction/sighash.rs
- src/tests/transaction/typeid.rs
- src/transaction/builder/mod.rs
- src/transaction/handler/mod.rs
- src/transaction/handler/multisig.rs
- src/transaction/handler/sighash.rs
- src/transaction/handler/typeid.rs
- src/transaction/input/mod.rs
- src/transaction/mod.rs
- src/types/script_id.rs
base on https://github.com/nervosnetwork/ckb-sdk-rust/pull/76, refactor https://github.com/nervosnetwork/ckb-sdk-rust/pull/75
> feat: add TypeId handler

- Cargo.toml
And make it easier to use vendored native-tls or rustls.
> feat: make reqwest default-tls optional

- .github/workflows/ci.yaml
- src/rpc/ckb.rs
- src/tests/ckb_indexer_rpc.rs
> Fix `get_fee_rate_statics` param, Fix `cargo-deny` installation, Fix CI `test_get_indexer_tip`

- Cargo.toml
- src/rpc/ckb.rs
- src/test_util.rs
- src/tests/ckb_rpc.rs
- src/tests/cycle.rs
- src/traits/default_impls.rs
- src/traits/dummy_impls.rs
- src/traits/light_client_impls.rs
- src/traits/mod.rs
- src/traits/offchain_impls.rs
- src/tx_builder/mod.rs
- src/types/address.rs
> Upgrade ckb dependencies to `v0.111.0`

- .github/workflows/ci.yaml
This PR want to close #95, add `cargo build --examples` check on CI workflow.
> Add `cargo build --examples` check on CI

- src/rpc/ckb.rs
add `generate_epochs`.
issue:
- https://github.com/nervosnetwork/ckb-cli/issues/570
> add rpc generate_epochs.

- Cargo.toml
- deny.toml
- src/rpc/ckb.rs
- src/tests/cycle.rs
- src/traits/offchain_impls.rs
> Upgrade `ckb` dependencies to `v0.114.0`, bump `ckb-sdk` to `3.1.0`

- Cargo.toml
- README.md
> Bump ckb-sdk-rust to 3.2.1

- Cargo.toml
- src/traits/default_impls.rs
- src/util.rs
> Bump ckb dependencies to v0.117.0

- .github/workflows/ci.yaml
- Cargo.toml
- README.md
- deny.toml
- src/util.rs
Upgrade ckb dependencies to v0.200.0
> Upgrade ckb_dependencies to v0.200.0

- src/traits/default_impls.rs
> fix: fix method wrong impl

- Cargo.toml
- README.md
- src/test_util.rs
- src/tx_builder/mod.rs
- **Upgrade ckb_dependencies to v0.202.0**
- **Bump `ckb-sdk-rust` to `4.1.0`**
> Upgrade ckb dependencies to v0.202.0, Bump ckb-sdk-rust to `4.1.0`

- .github/workflows/release.yml
> Fix workflows/release.yml

- Cargo.toml
- README.md
> Bump `ckb-sdk-rust` to `4.2.0`

- src/rpc/mod.rs
Add `with_builder` function for CkbRpcClient, then we can make such usage:
```rust
let _client: CkbRpcClient =
CkbRpcClient::with_builder("291", |client_builder: reqwest::ClientBuilder| {
client_builder
.timeout(std::time::Duration::from_secs(1))
.connect_timeout(std::time::Duration::from_secs(1))
})
.unwrap();
```
Request for comment. @quake @zhangsoledad @driftluo
> Add `with_builder` for `CkbRpcClient`

- Cargo.toml
- README.md
> Bump `ckb-sdk-rust` to `4.3.0`
